default:
  tags:
    - docker-autoscaling

stages:
  - build
  - tagging
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

# Build Docs
Build Image:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  image: docker:stable
  services:
    - docker:dind
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/docs:${CI_COMMIT_SHA} -f .devcontainer/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/docs:${CI_COMMIT_SHA}
  only:
    - master
    - merge_requests


.Tag Image:
  variables:
    GIT_STRATEGY: none
  stage: tagging
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/docs:${CI_COMMIT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}/docs:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/docs:${IMAGE_TAG}
    - docker push ${CI_REGISTRY_IMAGE}/docs:${IMAGE_TAG}
    
Tag Latest:
  extends: .Tag Image
  variables:
    IMAGE_TAG: latest
  only:
    - master

Tag Dev:
  extends: .Tag Image
  variables:
    IMAGE_TAG: dev
  only:
    - merge_requests


.Update Environment:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl --kubeconfig=/tmp/kubeconfig set image -n ${NAMESPACE} deployment/${NAMESPACE} ${NAMESPACE}=${CI_REGISTRY_IMAGE}/docs:${CI_COMMIT_SHA}
  dependencies: []

Update Prod:
  extends: .Update Environment
  variables:
    NAMESPACE: gec-docs
  before_script:
    - echo ${PROD_GEC_DOCS_KUBECONFIG} | base64 -d > /tmp/kubeconfig
  only: 
    - master

Update Dev:
  extends: .Update Environment
  variables:
    NAMESPACE: dev-gec-docs
  before_script:
    - echo ${DEV_GEC_DOCS_KUBECONFIG} | base64 -d > /tmp/kubeconfig
  only:
    - merge_requests
