default:
  tags:
    - docker-autoscaling

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

# Build Docs
.Build Image:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  image: docker:20.10.3
  services:
    - docker:dind
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE/docs:devcontainer || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/docs:devcontainer --tag $CI_REGISTRY_IMAGE/docs:devcontainer --target devcontainer -f .devcontainer/Dockerfile .
    
    - docker build --cache-from $CI_REGISTRY_IMAGE/docs:devcontainer --tag $CI_REGISTRY_IMAGE/docs:${CI_COMMIT_SHA} --tag $CI_REGISTRY_IMAGE/docs:${IMAGE_TAG} --file .devcontainer/Dockerfile .
    - docker image push --all-tags $CI_REGISTRY_IMAGE/docs
  only:
    - master
    - merge_requests
    
Build Latest:
  extends: .Build Image
  variables:
    IMAGE_TAG: latest
  only:
    - master

Build Dev:
  extends: .Build Image
  variables:
    IMAGE_TAG: dev
  only:
    - merge_requests


.Update Environment:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl --kubeconfig=/tmp/kubeconfig set image -n ${NAMESPACE} deployment/${NAMESPACE} ${NAMESPACE}=${CI_REGISTRY_IMAGE}/docs:${CI_COMMIT_SHA}
  dependencies: []

Update Prod:
  extends: .Update Environment
  variables:
    NAMESPACE: gec-docs
  before_script:
    - echo ${PROD_GEC_DOCS_KUBECONFIG} | base64 -d > /tmp/kubeconfig
  only: 
    - master

Update Dev:
  extends: .Update Environment
  variables:
    NAMESPACE: dev-gec-docs
  before_script:
    - echo ${DEV_GEC_DOCS_KUBECONFIG} | base64 -d > /tmp/kubeconfig
  only:
    - merge_requests
