# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Optimist Documentation
  de: Optimist Dokumentation
language:
  en: English
  de: Deutsch
description:
  en: TODO
  de: TODO
index:
  en:
  de: de/home/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.innovo.cloud" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  - scope:
      type: "pages"
    values:
      header: false

collections:
  optimist:
    output: true
  #imke:
  #  output: true

collections_dir: docs