# Site settings
title: Documentation
description: Documentation

# URLs
baseurl: ""
url: ""
permalink: pretty

# Theme
theme: "just-the-docs"
color_scheme: gec

# i18n
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["_sass", "README.md"]
# WORKAROUND: Disable parallel builds due to Windows systems not supporting this feature
# See <https://github.com/untra/polyglot#compatibility>
parallel_localization: false

# Footer
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true
last_edit_time_format: "%F"

# Plugins
plugins:
  - jekyll-polyglot

# Styles
# WORKAROUND
# We disable sourcemaps, otherwhise i18n via polyglot leads to broken styles compiled from scss
# See <https://github.com/untra/polyglot#compatibility>, <https://github.com/untra/polyglot/issues/107#issuecomment-598274075>
sass:
  sourcemap: never

# Markdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Build
exclude:
  [
    "node_modules/",
    "just-the-docs.gemspec",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "docs/tests/",
  ]
