# Site settings
title: Documentation
description: Documentation

baseurl: ''
url: ''

permalink: pretty
exclude:
  [
    'node_modules/',
    'just-the-docs.gemspec',
    'Gemfile',
    'Gemfile.lock',
    'package.json',
    'package-lock.json',
    'script/',
    'LICENSE.txt',
    'lib/',
    'bin/',
    'README.md',
    'Rakefile',
    'docs/tests/'
  ]

theme: 'just-the-docs'
color_scheme: gec

languages: ['en', 'de']
default_lang: 'en'
exclude_from_localization: ['assets', '_scss', 'README.md']

# WORKAROUND
# Windows system to not support this feature
# See <https://github.com/untra/polyglot#compatibility>
parallel_localization: false

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Back to top link
back_to_top: true
back_to_top_text: 'Back to top'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: '%b %e %Y at %I:%M %p' # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

plugins:
  - jekyll-polyglot

# WORKAROUND
# We disable sourcemaps, otherwhise i18n via polyglot leads to broken styles compiled from scss
# See <https://github.com/untra/polyglot#compatibility>, <https://github.com/untra/polyglot/issues/107#issuecomment-598274075>
sass:
  sourcemap: never

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
